apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservices-monitor
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - microservices

  selector:
    matchLabels:
      app: microservice

  endpoints:
  - port: http
    path: /metrics
    interval: 15s
