apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservices-monitor
  namespace: microservices
spec:
  selector:
    matchLabels:
      app: service-a
  endpoints:
  - port: http
    path: /metrics
