apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: observability
spec:
  selector:
    app: jaeger
  ports:
  - name: http
    port: 16686
    targetPort: 16686
  type: ClusterIP
